/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2;

/**
 *
 * @author fvg
 */
import sonidopapa.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.*;

import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

public class MusicaConInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form MusicaConInterfaz
     */
    String Musica[];
    Player ply;
    String Cancion;
    int BanderaGuardar = 0;
    File musica;
    Pruebitaas Instancia = new Pruebitaas();
    public static boolean bandera = true, Stop = true;

    public MusicaConInterfaz() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reproductor de Música");

        PedirCarpeta();
        LlenarVector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelCancion = new javax.swing.JLabel();
        ComboCanciones = new javax.swing.JComboBox();
        BotonPausaOPlay = new javax.swing.JButton();
        BotonReproducirOStop = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelCancion.setText("Canción: ");

        ComboCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCancionesActionPerformed(evt);
            }
        });

        BotonPausaOPlay.setText("Pausa");
        BotonPausaOPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausaOPlayActionPerformed(evt);
            }
        });

        BotonReproducirOStop.setText("Reproducir");
        BotonReproducirOStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReproducirOStopActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Eliminar datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ComboCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelCancion))
                .addGap(0, 746, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(BotonReproducirOStop)
                .addGap(18, 18, 18)
                .addComponent(BotonPausaOPlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelCancion)
                .addGap(33, 33, 33)
                .addComponent(ComboCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPausaOPlay)
                    .addComponent(BotonReproducirOStop)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCancionesActionPerformed
        Cancion = ComboCanciones.getSelectedItem().toString();

        try {
            if (Cancion.equals("") || Cancion.equals(" ") || Cancion.equals("  ") || Cancion.equals("   ")) {
                LabelCancion.setText("Canción: ");
            } else {
                LabelCancion.setText("Canción: " + Cancion);
                //ply = new Player(new FileInputStream("C:\\Users\\fvg\\Downloads\\Musica\\" + Cancion));
            }

        } catch (/*FileNotFoundException | JavaLayer*/Exception ex) {
            System.err.print(ex);
        }
    }//GEN-LAST:event_ComboCancionesActionPerformed
    int BanderaInt = 0;
    private void BotonPausaOPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausaOPlayActionPerformed
        if (bandera == true) {
            bandera = false;
            BotonPausaOPlay.setText("Play");
        } else {
            bandera = true;
            BotonPausaOPlay.setText("Pausa");
        }
    }//GEN-LAST:event_BotonPausaOPlayActionPerformed

    private void BotonReproducirOStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReproducirOStopActionPerformed

        Pruebitaas p = new Pruebitaas();
        if (BanderaInt == 0) {

            p.Sonar(Cancion, musica.getAbsolutePath());
            p.start();
            bandera = true;
            Stop = true;
            BanderaInt++;
            BotonReproducirOStop.setText("Stop");
        } else {
            BanderaInt = 0;
            BotonReproducirOStop.setText("Reproducir");
            parar();
        }


    }//GEN-LAST:event_BotonReproducirOStopActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        File ArchivoGuardado = new File("C:\\Reproductor\\Carpeta.ddr");
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(ArchivoGuardado))) {
            oos.writeBytes("");
        } catch (Exception e) {
            System.err.println("Error en la Escritura del archivo de creado Localizacion: metodo GuardarRuta() " + e);
        }
        
        JOptionPane.showMessageDialog(null, "Datos Eliminados");
        System.exit(0);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaConInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaConInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaConInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaConInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaConInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPausaOPlay;
    javax.swing.JButton BotonReproducirOStop;
    private javax.swing.JComboBox ComboCanciones;
    private javax.swing.JLabel LabelCancion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    void LlenarBox() {
        ComboCanciones.addItem("  ");
        for (int i = 0; i < Musica.length; i++) {
            ComboCanciones.addItem(Musica[i]);
        }
    }

    void LlenarVector() {

        FilenameFilter Filtro = new FilenameFilter() {

            @Override
            public boolean accept(File dir, String name) {
                if (name.endsWith(".mp3")) {
                    return true;
                } else {
                    return false;
                }
            }
        };

        String VectorMusica[] = musica.list(Filtro);
        Musica = VectorMusica;
        LlenarBox();
        //  System.out.println(musica.getAbsolutePath());
    }

    void parar() {
        bandera = false;
        Stop = false;
        BanderaInt = 0;
        Pruebitaas p = new Pruebitaas();
        p.stop();
    }

    private void Crear() {
        File CarpetaDatos = new File("C:\\Reproductor");
        File ArchivoGuardado = new File("C:\\Reproductor\\Carpeta.ddr");
        boolean Creado = false;
        while (!Creado) {
            if (CarpetaDatos.exists()) {
                if (ArchivoGuardado.exists()) {
                    Creado = true;

                } else {
                    try {
                        ArchivoGuardado.createNewFile();

                    } catch (Exception e) {
                        System.err.println("Error Creando el archivo Localizacion: metodo Crear() " + e);
                    }
                }
            } else {
                CarpetaDatos.mkdir();
            }

        }
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(ArchivoGuardado))) {
            oos.writeBytes("");
        } catch (Exception e) {
            System.err.println("Error en la Escritura del archivo de creado Localizacion: metodo Crear() " + e);
        }
    }

    private void PedirCarpeta() {

        File ArchivoGuardado = new File("C:\\Reproductor\\Carpeta.ddr");
        if (!ArchivoGuardado.exists()) {
            Crear();
            PedirCarpeta();
        } else {
            try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(ArchivoGuardado))) {
                int Lector = ois.read();
                //System.out.println(Lector);
                String Ruta = "";
                if (Lector != -1) {
                   // System.out.println("Prueva");
                    int Caracter = 0;
                    do {
                        Caracter = ois.read();
                        if (Caracter != -1) {

                            Ruta = Ruta + (char) Caracter;
                        }
                    } while (Caracter != -1);
                    musica = new File(Ruta);;
                } else {
                    File CarpetaMusica;
                    try {
                        JOptionPane.showMessageDialog(null, "Ahora Seleccione Una carpeta");
                        JFileChooser Jfc = new JFileChooser();
                        Jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                        int i = Jfc.showOpenDialog(this);
                        if (i == JFileChooser.APPROVE_OPTION) {
                            CarpetaMusica = Jfc.getSelectedFile();
                            //System.out.println(CarpetaMusica.getAbsolutePath());
                            try {
                                String Opciones[] = new String[2];
                                Opciones[0] = "Solo una vez";
                                Opciones[1] = "Siempre";
                                int Seleccion = JOptionPane.showOptionDialog(this, "Esta Carpeta La usaras", "Eleccion", 0, JOptionPane.QUESTION_MESSAGE, null, Opciones, null);
                                //System.out.println(Seleccion);
                                if (Seleccion == 0) {
                                    musica = new File(CarpetaMusica.getAbsolutePath());
                                } else if (Seleccion == 1) {
                                    musica = new File(CarpetaMusica.getAbsolutePath());
                                    GuardarRuta(CarpetaMusica.getAbsolutePath());
                                    
                                } else {
                                    JOptionPane.showMessageDialog(null, "Error Inesperado");
                                    System.exit(0);
                                }
                            } catch (Exception e) {
                                System.err.println("Error en el metodo PedirCarpeta() " + e);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Error");
                            System.exit(0);
                        }
                    } catch (Exception e) {
                        System.err.println("Error Pidiendo la carpeta Localizacion: metodo PedirCarpeta() " + e);
                    }
                }

            } catch (Exception e) {
                System.err.println("Error leyendo el archivo de guardado localizacion: metodo PedirCarpeta() " + e);
            }

        }

    }

    private void GuardarRuta(String Ruta) {
        File ArchivoGuardado = new File("C:\\Reproductor\\Carpeta.ddr");
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(ArchivoGuardado))) {
            oos.writeBytes("X" + Ruta);
        } catch (Exception e) {
            System.err.println("Error en la Escritura del archivo de creado Localizacion: metodo GuardarRuta() " + e);
        }
    }
    
    
    public void BotonDeStop(){
        Pruebitaas p = new Pruebitaas();
        if (BanderaInt == 0) {

            p.Sonar(Cancion, musica.getAbsolutePath());
            p.start();
            bandera = true;
            Stop = true;
            BanderaInt++;
            BotonReproducirOStop.setText("Stop");
        } else {
            BanderaInt = 0;
            BotonReproducirOStop.setText("Reproducir");
            parar();
        }
    }
}
